<?php

namespace App\Exports;

use App\Services\ReportSummaryBuilder;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

class ReportExport implements FromCollection, ShouldAutoSize, WithEvents, WithHeadings, WithMapping
{
    public function __construct(
        private string $type,
        private Collection $rows,
        private ?string $dateFrom = null,
        private ?string $dateTo = null,
    ) {
    }

    public function collection()
    {
        return $this->rows;
    }

    public function headings(): array
    {
        return match ($this->type) {
            'inventory' => ['ID', 'Product', 'Quantity', 'Status'],
            'orders' => ['ID', 'Date', 'Status', 'Supplier'],
            'returns' => ['ID', 'Transaction ID', 'Product', 'Quantity', 'Reason', 'Cashier', 'Status', 'Date'],
            'damage' => ['ID', 'Date', 'Product', 'Supplier', 'Quantity', 'Damage Type', 'Status'],
            'supplier' => ['ID', 'Supplier', 'Status', 'Total Orders', 'Total Amount'],
            default => ['ID', 'Date', 'Amount', 'Customer', 'Payment Method'],
        };
    }

    public function map($row): array
    {
        return match ($this->type) {
            'inventory' => [
                $row->InventoryID,
                $row->product?->ProductName ?? 'N/A',
                $row->Quantity,
                $row->Status,
            ],
            'orders' => [
                $row->PurchaseOrderID,
                $row->PurchaseDate,
                $row->Status,
                $row->supplier?->SupplierName ?? 'N/A',
            ],
            'returns' => [
                $row->SalesReturnID,
                $row->SalesTransactionID,
                $row->product?->ProductName ?? 'N/A',
                $row->Quantity,
                $row->Reason,
                $row->CashierName,
                $row->Status,
                $row->ReturnDate,
            ],
            'damage' => [
                $row->DamageID,
                optional($row->DateRecorded)->format('Y-m-d'),
                $row->product?->ProductName ?? 'N/A',
                $row->supplier?->SupplierName ?? 'N/A',
                $row->Quantity,
                \App\Models\DamagedProduct::DAMAGE_TYPES[$row->DamageType] ?? $row->DamageType,
                $row->Status,
            ],
            'supplier' => [
                $row->SupplierID,
                $row->SupplierName,
                $row->Status,
                $row->TotalOrders,
                $row->TotalAmount,
            ],
            default => [
                $row->BillingID,
                $row->BillingDate,
                $row->BillingAmount,
                $row->CustomerName ?? 'N/A',
                $row->payment?->PaymentMethod ?? 'N/A',
            ],
        };
    }

    // The column (1-indexed) holding a currency amount in the data grid
    // itself, if this type has one — used both to apply a currency cell
    // format to that column and to build a real SUM() formula for the
    // matching Report Summary row, instead of a hardcoded value.
    private function moneyColumn(): ?int
    {
        return match ($this->type) {
            'sales' => 3,
            'supplier' => 5,
            default => null,
        };
    }

    private function dateColumn(): ?int
    {
        return match ($this->type) {
            'sales', 'orders', 'damage' => 2,
            'returns' => 8,
            default => null,
        };
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();
                $columnCount = count($this->headings());
                $lastColumnLetter = Coordinate::stringFromColumnIndex($columnCount);
                $dataRowCount = $this->rows->count();

                // ---- Title block, inserted above the heading/data grid ----
                $period = ($this->dateFrom || $this->dateTo)
                    ? ($this->dateFrom ?: 'Earliest') . ' to ' . ($this->dateTo ?: 'Latest')
                    : 'All Time';

                $titleRows = [
                    ['CCTV EXPRESS TRADING'],
                    ['Point of Sale & Inventory System'],
                    [ucfirst($this->type) . ' Report'],
                    [],
                    ['Report Period', $period],
                    ['Generated By', auth()->user()->full_name ?? 'N/A'],
                    ['Generated On', now()->format('F j, Y g:i A')],
                    ['Branch', 'Main Branch'],
                    [],
                    ['FILTERS'],
                    ['Date Range', $period],
                    [],
                ];
                $offset = count($titleRows);

                $sheet->insertNewRowBefore(1, $offset);
                foreach ($titleRows as $i => $cells) {
                    foreach ($cells as $col => $value) {
                        $sheet->setCellValueByColumnAndRow($col + 1, $i + 1, $value);
                    }
                }
                $sheet->mergeCells("A1:{$lastColumnLetter}1");
                $sheet->mergeCells("A2:{$lastColumnLetter}2");
                $sheet->mergeCells("A3:{$lastColumnLetter}3");
                $sheet->getStyle('A1:A3')->getFont()->setBold(true);
                $sheet->getStyle('A1')->getFont()->setSize(14);
                $sheet->getStyle('A1:A3')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
                $sheet->getStyle('A5:A8')->getFont()->setBold(true);
                $sheet->getStyle('A10')->getFont()->setBold(true);

                // ---- Header row + data ----
                $headerRow = $offset + 1;
                $dataStartRow = $headerRow + 1;
                $dataEndRow = $headerRow + $dataRowCount;

                $sheet->getStyle("A{$headerRow}:{$lastColumnLetter}{$headerRow}")->getFont()->setBold(true);
                $sheet->getStyle("A{$headerRow}:{$lastColumnLetter}{$headerRow}")->getFill()
                    ->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('E2E8F0');
                $sheet->setAutoFilter("A{$headerRow}:{$lastColumnLetter}{$headerRow}");
                $sheet->freezePane('A' . $dataStartRow);

                if ($moneyCol = $this->moneyColumn()) {
                    $letter = Coordinate::stringFromColumnIndex($moneyCol);
                    if ($dataRowCount > 0) {
                        $sheet->getStyle("{$letter}{$dataStartRow}:{$letter}{$dataEndRow}")
                            ->getNumberFormat()->setFormatCode('#,##0.00');
                    }
                }
                if ($dateCol = $this->dateColumn()) {
                    $letter = Coordinate::stringFromColumnIndex($dateCol);
                    if ($dataRowCount > 0) {
                        $sheet->getStyle("{$letter}{$dataStartRow}:{$letter}{$dataEndRow}")
                            ->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_DATE_YYYYMMDD2);
                    }
                }

                // ---- Report Summary, editable cells with a formula where
                // it maps onto a real column in this type's data grid ----
                $summaryRow = $dataEndRow + 2;
                $sheet->setCellValue("A{$summaryRow}", 'REPORT SUMMARY');
                $sheet->getStyle("A{$summaryRow}")->getFont()->setBold(true);
                $summaryRow++;

                $moneyLetter = $this->moneyColumn() ? Coordinate::stringFromColumnIndex($this->moneyColumn()) : null;
                $moneyLabel = match ($this->type) {
                    'sales' => 'Net Sales',
                    'supplier' => 'Total Amount',
                    default => null,
                };

                foreach (ReportSummaryBuilder::forType($this->type, $this->rows) as $entry) {
                    $sheet->setCellValue("A{$summaryRow}", $entry['label']);

                    if ($moneyLetter && $dataRowCount > 0 && $entry['label'] === $moneyLabel) {
                        $sheet->setCellValue("B{$summaryRow}", "=SUM({$moneyLetter}{$dataStartRow}:{$moneyLetter}{$dataEndRow})");
                    } else {
                        $sheet->setCellValue("B{$summaryRow}", $entry['value']);
                    }

                    if ($entry['money']) {
                        $sheet->getStyle("B{$summaryRow}")->getNumberFormat()->setFormatCode('#,##0.00');
                    }

                    $summaryRow++;
                }
            },
        ];
    }
}
