<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($type) }} Report</title>
    <style>
        body { font-family: sans-serif; font-size: 11px; color: #1a1a1a; }
        .company-header { text-align: center; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; margin-bottom: 12px; }
        .company-header h1 { margin: 0; font-size: 18px; letter-spacing: 0.04em; }
        .company-header p { margin: 2px 0 0; color: #555; font-size: 10px; }
        h2.report-title { font-size: 15px; margin: 0 0 4px; text-transform: capitalize; text-align: center; }
        p.meta { color: #555; margin: 2px 0; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 14px; }
        th, td { border: 1px solid #ccc; padding: 5px 7px; text-align: left; }
        th { background: #f0f0f0; }
        p.grand-total { text-align: right; font-weight: bold; margin-top: 10px; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 9px; color: #777; }
        .pagenum:before { content: counter(page) " of " counter(pages); }
    </style>
</head>
<body>
    <div class="footer">Page <span class="pagenum"></span></div>

    <div class="company-header">
        <h1>CCTV Express</h1>
        <p>Your Trusted Security Partner</p>
    </div>

    <h2 class="report-title">{{ $type }} Report</h2>
    <p class="meta">
        @if($dateFrom || $dateTo)
            Date Range: {{ $dateFrom ?: 'Earliest' }} to {{ $dateTo ?: 'Latest' }}
        @else
            Date Range: All Time
        @endif
    </p>
    <p class="meta">Generated By: {{ auth()->user()->full_name ?? 'N/A' }} &middot; Generated: {{ now()->format('F j, Y g:i A') }}</p>

    @include('admin.reports.partials.print-table', ['type' => $type, 'rows' => $rows])
</body>
</html>
