<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($type) }} Report</title>
    <style>
        body { font-family: sans-serif; font-size: 13px; color: #1a1a1a; max-width: 900px; margin: 0 auto; padding: 30px; }
        .company-header { text-align: center; border-bottom: 2px solid #1a1a1a; padding-bottom: 14px; margin-bottom: 14px; }
        .company-header h1 { margin: 0; font-size: 22px; letter-spacing: 0.04em; }
        .company-header p { margin: 4px 0 0; color: #555; font-size: 12px; }
        h2.report-title { font-size: 16px; margin: 0 0 4px; text-transform: capitalize; text-align: center; }
        p.meta { color: #555; margin: 2px 0; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border: 1px solid #ccc; padding: 7px 9px; text-align: left; }
        th { background: #f0f0f0; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
        p.grand-total { text-align: right; font-weight: bold; margin-top: 12px; }
        .print-btn { position: fixed; top: 20px; right: 20px; padding: 10px 20px; background: #3b82f6; color: white; border: none; border-radius: 6px; cursor: pointer; }
        @media print { .no-print { display: none; } body { padding: 0; } }
    </style>
</head>
<body>
    <button class="print-btn no-print" onclick="window.print()">Print</button>

    <div class="company-header">
        <h1>CCTV Express</h1>
        <p>Your Trusted Security Partner</p>
    </div>

    <h2 class="report-title">{{ $type }} Report</h2>
    <p class="meta">
        @if($dateFrom || $dateTo)
            Date Range: {{ $dateFrom ?: 'Earliest' }} to {{ $dateTo ?: 'Latest' }}
        @else
            Date Range: All Time
        @endif
    </p>
    <p class="meta">Generated By: {{ auth()->user()->full_name ?? 'N/A' }} &middot; Generated: {{ now()->format('F j, Y g:i A') }}</p>

    @include('admin.reports.partials.print-table', ['type' => $type, 'rows' => $rows])
</body>
</html>
