{{-- Shared report header — company branding, title, period, generator, and
     a Filters block. Included by both admin/reports/pdf.blade.php and
     admin/reports/print.blade.php so the two surfaces never drift out of
     sync with each other. Expects: $type, $dateFrom, $dateTo.
     Company logo renders as text-only (no logo asset exists in this
     project); Branch is a hardcoded label since no multi-branch concept
     exists in the schema — both match how every other printed document in
     this app already handles company branding. The Filters block only
     lists Date Range because that's the only real filter this report
     module has today; listing Category/Supplier/Payment Method/Cashier as
     "All" would misrepresent the document since none of them actually
     filter anything yet. --}}
<div class="company-header">
    <h1>CCTV Express</h1>
    <p>Your Trusted Security Partner</p>
</div>

<h2 class="report-title">{{ $type }} Report</h2>

<div class="report-meta">
    <p><strong>Report Period:</strong>
        @if($dateFrom || $dateTo)
            {{ $dateFrom ? \Illuminate\Support\Carbon::parse($dateFrom)->format('F j, Y') : 'Earliest' }}
            &ndash;
            {{ $dateTo ? \Illuminate\Support\Carbon::parse($dateTo)->format('F j, Y') : 'Latest' }}
        @else
            All Time
        @endif
    </p>
    <p><strong>Generated By:</strong> {{ auth()->user()->full_name ?? 'N/A' }}</p>
    <p><strong>Generated On:</strong> {{ now()->format('F j, Y g:i A') }}</p>
    <p><strong>Branch:</strong> Main Branch</p>
</div>

<div class="report-filters">
    <div class="report-filters-title">Filters</div>
    <p><strong>Date Range:</strong>
        @if($dateFrom || $dateTo)
            {{ $dateFrom ?: 'Earliest' }} to {{ $dateTo ?: 'Latest' }}
        @else
            All Time
        @endif
    </p>
</div>
