{{-- Shared report footer + signature block, rendered once at the true end
     of the document content (normal flow, not position:fixed — a repeating
     page footer with page numbers is handled separately in pdf.blade.php's
     own <style>, since dompdf's counter(page) trick needs a dedicated fixed
     element and would wrongly repeat a signature block on every page).
     Included by both admin/reports/pdf.blade.php and
     admin/reports/print.blade.php. Expects: $pdf (bool) — PDF additionally
     gets "Confidential Report". Signature captions are generic role
     labels, not real tracked names — this report module has no approval
     workflow, unlike Purchase Orders. --}}
<div class="signature-area">
    <div class="signature-block">
        <div class="signature-line">&nbsp;<br><small>Administrator</small><br><small class="sig-caption">Prepared By</small></div>
    </div>
    <div class="signature-block">
        <div class="signature-line">&nbsp;<br><small>Manager</small><br><small class="sig-caption">Checked By</small></div>
    </div>
    <div class="signature-block">
        <div class="signature-line">&nbsp;<br><small>Owner</small><br><small class="sig-caption">Approved By</small></div>
    </div>
</div>

<div class="doc-footer-inline">
    Generated by CCTV Express POS &amp; Inventory System
    @if($pdf ?? false)
        <br>Confidential Report
    @endif
</div>
